### PR TITLE
Updates to prepare dutchf3

### PR DESCRIPTION
**Pull request by kirasoderstrom**
This PR includes:

- Renaming of patch to patch_size when the dutchf3 script uses patch size #182 
- Modifying the range function to use patch_size when it is creating crosslines and inlines #164 #183 
- Modifying the range function further to grab expected indices #184 
- Updates to get_data_for_builds.sh to allow build to succeed

#164  #182 #184 #183

### CODE REVIEW

**Comment by maxkazmsft** [comment]
I see possible merge conflicts with Yazeed's PR https://github.com/microsoft/seismic-deeplearning/pull/183 but the content looks very similar - approving

**Comment by yalaudah** [comment]
I think this one is more comprehensive, so we can move forward with this PR instead of https://github.com/microsoft/seismic-deeplearning/pull/183. 

But since this also changes `patch` to `patch_size` is should cover a few other places where `patch` is still being used. Files like `ablation_study.sh` ,`README.md`.

**Comment by kirasoderstrom** [comment]
@yalaudah I updated ablation.sh, where is ablation_study.sh located or are these the same? Additionally, the README.md in scripts does not look like it needs modification but let me know what you think 
image

**Comment by yalaudah** [comment]
@kirasoderstrom  I could be missing something.. but shouldn't `--patch` in the readme (line 150) be updated to `--patch_size` too? 
``` 
python prepare_dutchf3.py split_train_val patch --data-dir=${data_dir}/data --stride=50 --**patch**=100
```

**Comment by kirasoderstrom** [comment]
Closing this PR @yalaudah, I'll open another task for the ablation.sh component and continue investigating that

**Pull request merged**
